name: Generate and Push Release Notes
on:
  push:
    tags:
      - '*.*.*'
jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-2.8.0-x86_64-unknown-linux-gnu.tar.gz  | tar -xz
          sudo mv git-cliff-2.8.0 /usr/local/bin/git-cliff/

      - name: Generate changelog
        run: /usr/local/bin/git-cliff/git-cliff -o CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin
          git checkout -b pages || git checkout pages
          git branch --set-upstream-to=origin/pages pages
          git pull
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.ref_name }}"
          git push origin pages || git push -u origin pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}